services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3009:3000'
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://172.17.0.1:3010
      - HOSTNAME=0.0.0.0
      # Add your environment variables here
    volumes:
      # Mount .env.local for local development overrides
      - ./.env.local:/app/.env.local:ro
    restart: unless-stopped
    container_name: tutors-client

networks:
  default:
    name: tutors-network
